<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>prioritized_qp_osqp</name>
  <version>0.0.0</version>
  <description>The prioritized_qp_osqp package</description>

  <maintainer email="hiraoka@jsk.imi.i.u-tokyo.ac.jp">Naoki-Hiraoka</maintainer>

  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>prioritized_qp_base</depend>
  <depend>osqp-cpp</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
